[build]
  publish = "."
  # (optional but faster/cleaner) use npm ci if you commit package-lock.json
  command = "npm install && node scripts/write-sa-key.mjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # include ALL node modules your functions import at runtime
  external_node_modules = [
    "google-auth-library",
    "google-spreadsheet",
    "jsonwebtoken",
    "googleapis" # <-- add this
  ]
  included_files = ["netlify/functions/sa_key.pem"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Access-Control-Allow-Origin = "*"
    # <-- add X-Admin-Secret so the POST from Zapier is allowed
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Admin-Secret"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

