[build]
  publish = "."
  command = "npm install && node scripts/write-sa-key.js"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["google-auth-library","google-spreadsheet","jsonwebtoken"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

